# Generated by Django 5.1.15 on 2026-09-25 08:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('evaluating', 'Evaluating'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('requirements_assumptions', models.TextField(blank=True, default='')),
                ('classes_responsibilities', models.TextField(blank=True, default='')),
                ('relationships_interfaces', models.TextField(blank=True, default='')),
                ('workflows', models.TextField(blank=True, default='')),
                ('tradeoffs', models.TextField(blank=True, default='')),
                ('edge_cases', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.CharField(max_length=280)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=16)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('estimated_minutes', models.PositiveIntegerField(default=45)),
                ('description', models.TextField()),
                ('functional_requirements', models.JSONField(blank=True, default=list)),
                ('constraints', models.JSONField(blank=True, default=list)),
                ('design_considerations', models.JSONField(blank=True, default=list)),
                ('edge_cases', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('submitted', 'Submitted'), ('evaluating', 'Evaluating'), ('completed', 'Completed'), ('failed', 'Failed')], default='submitted', max_length=16)),
                ('provider', models.CharField(choices=[('rule_based', 'Rule based'), ('llm', 'LLM')], default='rule_based', max_length=16)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('rubric_results', models.JSONField(blank=True, default=list)),
                ('overall_feedback', models.TextField(blank=True, default='')),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('improvements', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='practice.attempt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='practice.problem'),
        ),
    ]
